# Generated by Django 5.0.7 on 2024-09-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courses',
            name='sem_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_no',
            field=models.IntegerField(null=True),
        ),
    ]
