# Generated by Django 5.0.7 on 2024-09-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_student_phone_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
    ]
