# Generated by Django 5.0.7 on 2024-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_remove_teacher_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='stts',
            field=models.IntegerField(default=0),
        ),
    ]
