# Generated by Django 5.0.7 on 2024-09-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0010_student_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
    ]
