# Generated by Django 5.0.7 on 2024-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0012_department_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='short_name',
            field=models.CharField(default=models.CharField(max_length=150), max_length=150),
        ),
    ]
