# Generated by Django 5.0.7 on 2024-09-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0014_classes_created_on_classes_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='department_id',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_in_charge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='end_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='classes',
            name='start_year',
            field=models.IntegerField(default=2020),
        ),
    ]
