# Generated by Django 5.0.7 on 2024-09-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0015_remove_classes_department_id_classes_class_in_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_year',
            field=models.IntegerField(default=2010),
        ),
    ]
