# Generated by Django 5.0.7 on 2024-09-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0018_remove_subjects_course_id_subjects_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teacher_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.teacher'),
        ),
    ]
