# Generated by Django 5.0.7 on 2024-09-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0019_subjects_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adm_no',
        ),
    ]
