# Generated by Django 5.0.7 on 2024-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0020_remove_student_adm_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='division_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
