# Generated by Django 5.0.7 on 2024-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0021_classes_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='passed_out',
            field=models.BooleanField(default=False),
        ),
    ]
