# Generated by Django 5.0.7 on 2024-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0022_classes_passed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
