# Generated by Django 5.0.7 on 2024-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0023_subjects_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
