# Generated by Django 5.0.7 on 2024-09-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0024_alter_subjects_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.courses'),
        ),
    ]
