# Generated by Django 5.0.7 on 2024-10-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0025_subjects_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adm_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='created_on',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_on',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_on',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_on',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
