# Generated by Django 5.0.7 on 2024-10-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0026_student_adm_no_student_dob_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rfid_string',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rfid_string',
        ),
    ]
