# Generated by Django 5.0.7 on 2024-10-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0028_assignsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='assignsub',
            name='teacher_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.teacher'),
        ),
    ]
