# Generated by Django 5.0.7 on 2024-10-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0029_remove_subjects_teacher_id_assignsub_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
    ]
