# Generated by Django 5.0.7 on 2024-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0030_remove_student_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
