# Generated by Django 5.0.7 on 2024-10-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0032_remove_subjects_sem_assignsub_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsub',
            name='sem',
        ),
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
