# Generated by Django 5.0.7 on 2024-10-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0033_remove_assignsub_sem_subjects_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sem',
        ),
        migrations.AddField(
            model_name='assignsub',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
