# Generated by Django 5.0.7 on 2024-10-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0034_remove_subjects_sem_assignsub_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.classes'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_and_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
