# Generated by Django 5.0.7 on 2024-10-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0038_timetableclass_rename_subject_timetable_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableclass',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usersApp.classes'),
        ),
        migrations.AddField(
            model_name='timetableclass',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
