# Generated by Django 5.0.7 on 2024-10-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0046_student_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adm_no',
        ),
    ]
