# Generated by Django 5.0.7 on 2024-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0047_remove_student_adm_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
